version: "3" 
services:

  postgres:
    image: postgres:latest
    container_name: intro_postgres
    ports:            
      - 5432:5432     
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=userdb_user
      - POSTGRES_PASSWORD=userdb_password
      - PGDATA=/var/lib/postgresql/db
    volumes:
      - postgres:/data/postgresql/db
volumes:
  postgres:



      
      
