server:
  port: 8080

spring:
  application:
    name: authsvc

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost/userdb"
    password: "userdb_password"
    username: "userdb_user"


config:
  oauth2:
    clientid: bobkoby5i_id
    clientSecret: bobkoby5i_secret
    accesstoken_validity_seconds: 3600
    refreshtoken_validity_seconds: 18000
    privateKey: -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA5ihK0u+UFJhGs3M5DZ7Py0rqZ55BnYh0oLOjT4JKH5U6gMeP
      4FfMxIg+DT2ydyeFX9FIjW/zbZmpSo9c4jFk24u1S29LnSzbUxC/HHuWrSd6TEC2
      pgEsPdbSEwAlro0l+wIP9pnDCx7laLP/LNwbH3UjVw20VP/PlXL0kQRUW5PfASBI
      Z7wkvFTh4VdYEfn6ciYoaX86DLV+4hIn/VldxUbbqlj0i5FoWSu/VHoi/81Y/HOq
      HebO1vUyCz2EmoWh1/qERKJ0Xigq4UKQZLJvUBXBGlzfqU4rT9FxaQT7y9LfXPZD
      ewXJKO+KKqIDwiQ+UuFctU2EL2UxVUAPtbdDPQIDAQABAoIBACl4TBcavOtDDsYp
      tjd6jIVcP8Ug0kDQw/bqtzvNxY5QRKTMkGODXm1xAQFAwyXOFK2Rl4mIiOuQGt1I
      3JsS/FHEqAtqB81PtksOwuieaiVT7ijMJjzeDDsuOFbdGW0MmLHUCs1LokWgMQS/
      HfTWyfpOkGoQmZQRLbWHa4KvrYV8VVlq3USQt/uhBRni09qwOUic6MvchvJR7RMf
      czlAX4yP/4mS/6VbNzkmd/cCqZ7EnCIoTCUEYzdT4zU9ACahKf2FEZ37JirBRRqm
      ehvyqtRgVLQcV+7iZUVnlztoB6n912U5Gv3+FMCvpjJjBt1rfew1TPo0zXiKP2GU
      +m9Axe8CgYEA6/JkZvHzgse095sp4iDtq81/Eg7jZ4nz8qWdbxw4gWF/MR2txm7X
      CqF07PgW/xVevJkuCZXIvYHxFLANjfMfzVWTG+yp5fSPEQVzzs7W9ZfDTDa1YJMR
      6dJ5BCLOf4Qt4+DKFatQrspoMc6xhIUEWluJYE9DnkyDfuJ68WBUsjcCgYEA+bfv
      qyTmB1pazrBzeAL5pFWKbeOan46QLOwMAO/hB9CWWr8VRhp/foV1FmxqlZTyE4gK
      pFnt04JHu0xKBj/UNSmddkK684xql1RMpzFFLX6hR+JikO9QXCjU6AtQugsxDgT6
      0kS1gnTknK5AOmApUwvsYHAEEsFGI5MYzNuTTCsCgYEAxbky+jH35riEppqY1q7R
      fQ+QVQm096dbjxPKgrobgBC8DeTZI1jvTDFRUuP0IX8/DL0xH0cuGeEyrit6sGH1
      XJVB2jzRg6sV2SXAjqY27UhomQ2foXadpFyEnTqt4Z5a9oQB1Xbi/hcQiey0RmFR
      7IaY8OR7vcRQzZvteylG0LECgYBawjI2RovgAkPcuR7OcG5g/sH4HG/XK85UtVnL
      gWONHo923doSh5Ds3/5lLvQx91dgJ+KORyz74W7GsPx6dvpedAiJsckWuWMIKxhM
      78hPt6VQZgQi3wea5zAyQeKOK4Ehskei4lwB1RA9rcskLEz4pO29QxkH4/zk8xJh
      ajCHzwKBgQDnDXfaCmUXURQSPzzPiUehoy30KNpHD6O5jHyh+KEonVkeg662WZdO
      W6RhKzgd8xNTyFHFaTDFv0Efbd3kac5JCGY3BeUFLt+GQkvDwNPmNLNe9DY+gd36
      KRfl845C/KUGoBRibSDMxHNk8acyusiaA+xdJD+/lXqdcA9qNhkdbw==
      -----END RSA PRIVATE KEY-----
    publicKey: -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5ihK0u+UFJhGs3M5DZ7P
      y0rqZ55BnYh0oLOjT4JKH5U6gMeP4FfMxIg+DT2ydyeFX9FIjW/zbZmpSo9c4jFk
      24u1S29LnSzbUxC/HHuWrSd6TEC2pgEsPdbSEwAlro0l+wIP9pnDCx7laLP/LNwb
      H3UjVw20VP/PlXL0kQRUW5PfASBIZ7wkvFTh4VdYEfn6ciYoaX86DLV+4hIn/Vld
      xUbbqlj0i5FoWSu/VHoi/81Y/HOqHebO1vUyCz2EmoWh1/qERKJ0Xigq4UKQZLJv
      UBXBGlzfqU4rT9FxaQT7y9LfXPZDewXJKO+KKqIDwiQ+UuFctU2EL2UxVUAPtbdD
      PQIDAQAB
      -----END PUBLIC KEY-----
