server:
  port: 8092

spring:
  application:
    name: products

security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkfMTK7Syts4et020y5iN
          eaE4ONv+eaK+MBNQy7KrFldEReN/VyxRK5/NV5qnDg/X5ti+DDgKz+RPRREqqqqa
          at2swvJY7WMvswdOli+P/0fHzorftOc+4aX1erLhant+BHQO4L/hnWORcG/5RoI2
          s7Hlto9U8A0O2PBhPvw0j0lgUOQp+0ou3avjrXBRRhhVtmo2xee1ZC0ELIdcMl6e
          45ktHGAIbPxr/z7A+lHX3H7dRGEcl5oWCEfLEvKChAYGxGkXuK1uWtYajbniLhmh
          83vDJcHwW92JOLdhADj03bt4tHqhchd/J2fZCqKPAC9KgRME3WcMUumvQbF9u7YH
          lwIDAQAB
          -----END PUBLIC KEY-----


#  jpa:
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#      generate-ddl: true
#    properties:
#      hibernate:
#        dialect=org:
#          hibernate:
#            dialect: PostgreSQL92Dialect
#            non_contextual_creation: true
#
#  datasource:
#    platform: postgres
#    driverClassName: "org.postgresql.Driver"
#    url: "jdbc:postgresql://localhost/userdb"
#    password: "userdb_password"
#    username: "userdb_user"



