server:
  port: 8081

spring:
  application:
    name: products

security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5ihK0u+UFJhGs3M5DZ7P
          y0rqZ55BnYh0oLOjT4JKH5U6gMeP4FfMxIg+DT2ydyeFX9FIjW/zbZmpSo9c4jFk
          24u1S29LnSzbUxC/HHuWrSd6TEC2pgEsPdbSEwAlro0l+wIP9pnDCx7laLP/LNwb
          H3UjVw20VP/PlXL0kQRUW5PfASBIZ7wkvFTh4VdYEfn6ciYoaX86DLV+4hIn/Vld
          xUbbqlj0i5FoWSu/VHoi/81Y/HOqHebO1vUyCz2EmoWh1/qERKJ0Xigq4UKQZLJv
          UBXBGlzfqU4rT9FxaQT7y9LfXPZDewXJKO+KKqIDwiQ+UuFctU2EL2UxVUAPtbdD
          PQIDAQAB
          -----END PUBLIC KEY-----


#  jpa:
#    database: POSTGRESQL
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#      generate-ddl: true
#    properties:
#      hibernate:
#        dialect=org:
#          hibernate:
#            dialect: PostgreSQL92Dialect
#            non_contextual_creation: true
#
#  datasource:
#    platform: postgres
#    driverClassName: "org.postgresql.Driver"
#    url: "jdbc:postgresql://localhost/userdb"
#    password: "userdb_password"
#    username: "userdb_user"



